[versions]
core = "1.16.0"
agp = "8.9.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
materialVersion = "1.11.0"
sqliteassethelper = "2.0.1"
workRuntime = "2.10.0"
mpandroidchart = "v3.1.0"
systembartint = "1.0.4"

[libraries]
core = { module = "androidx.core:core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
sqliteassethelper = { module = "com.readystatesoftware.sqliteasset:sqliteassethelper", version.ref = "sqliteassethelper" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
mpandroidchart = {group = "com.github.PhilJay", name = "mpandroidchart", version.ref = "mpandroidchart" }
systembartint = { module = "com.readystatesoftware.systembartint:systembartint", version.ref = "systembartint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

